import os
from PIL import Image

# Path to the source high-res logo generated by generate_image
source_logo = r"C:\Users\jatin\.gemini\antigravity-ide\brain\f2fbb3a4-5b4f-49ea-9a9a-3667df5a3d1f\echo_breaker_logo_1785400969545.png"
extension_dir = os.path.dirname(__file__)
icons_dir = os.path.join(extension_dir, "icons")
os.makedirs(icons_dir, exist_ok=True)

try:
    # Load source image
    img = Image.open(source_logo)
    
    # Save a copy as logo.png (original resolution)
    logo_path = os.path.join(icons_dir, "logo.png")
    img.save(logo_path)
    print(f"Copied original high-res logo to: {logo_path}")
    
    # Generate the standard extension sizes: 16x16, 48x48, 128x128
    sizes = [16, 48, 128]
    for size in sizes:
        resized_img = img.resize((size, size), Image.Resampling.LANCZOS)
        icon_path = os.path.join(icons_dir, f"icon{size}.png")
        resized_img.save(icon_path)
        print(f"Generated {icon_path} ({size}x{size})")

except Exception as e:
    print(f"Error generating icons: {e}")
